@Common.TestApi_HostAddress = https://localhost:7111

GET {{Common.TestApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Common.TestApi_HostAddress}}/api/barcode

###

POST {{Common.TestApi_HostAddress}}/api/usuario
Content-Type: application/json

{
  "username": "jorge",
  "email": "jorge@gmail.com"
}

###

@id=1
PUT {{Common.TestApi_HostAddress}}/api/usuario/{{id}}
Content-Type: application/json

{
  "username": "ivan.paz",
  "email": "ifer343@gmail.dev"
}

###

GET {{Common.TestApi_HostAddress}}/api/report

###

@ruc=1105246605001
@sriOnly=false
GET {{Common.TestApi_HostAddress}}/api/customer/GetRucSri?ruc={{ruc}}&sriOnly={{sriOnly}}

###

@ci=1105246605
GET {{Common.TestApi_HostAddress}}/api/customer/GetCedulaSri?ruc={{ci}}&sriOnly={{sriOnly}}

###

GET {{Common.TestApi_HostAddress}}/api/simplemodel/map-data-list

###
@pageIndex = 1
@pageSize = 10
GET {{Common.TestApi_HostAddress}}/api/usuario

###

DELETE {{Common.TestApi_HostAddress}}/api/usuario/{{id}}

###

@json="{"startDate": "2025-03-01", "endDate": "2025-03-31"}"
GET {{Common.TestApi_HostAddress}}/api/ats/download?json={"fromDate":"2025-03-01","toDate":"2025-03-31"}
###
